version: 2
workflows:
  version: 2
  build_test_ship_deploy:
      jobs:
        - build
jobs:
  build:
    working_directory: ~/project
    machine: true
    steps:
        - checkout
        - run:
            name: Docker Build 
            command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t   beatale/app:$TAG .
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push beatale/app:$TAG