version: 2
workflows:
  version: 2
  build_test_ship_deploy:
      jobs:
        - build
jobs:
  build:
    working_directory: ~/project
    docker:
    - image: php:7.2.14-apache
    steps:
    - run:
        name: Set Env
        command: |
            pwd  
            ls -lta
            date